language: python
python:
  - "2.6"
  - "2.7"

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblapack-dev libatlas-dev libblas-dev libgmp-dev libppl-dev
  - pip install -r requirements.txt

script:
  nosetests
